/*
 * Appwrite
 * Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: team@appwrite.io
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ModelFile
 */
public class ModelFileTest {
    private final ModelFile model = new ModelFile();

    /**
     * Model tests for ModelFile
     */
    @Test
    public void testModelFile() {
        // TODO: test ModelFile
    }

    /**
     * Test the property '$id'
     */
    @Test
    public void $idTest() {
        // TODO: test $id
    }

    /**
     * Test the property 'bucketId'
     */
    @Test
    public void bucketIdTest() {
        // TODO: test bucketId
    }

    /**
     * Test the property '$createdAt'
     */
    @Test
    public void $createdAtTest() {
        // TODO: test $createdAt
    }

    /**
     * Test the property '$updatedAt'
     */
    @Test
    public void $updatedAtTest() {
        // TODO: test $updatedAt
    }

    /**
     * Test the property '$permissions'
     */
    @Test
    public void $permissionsTest() {
        // TODO: test $permissions
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'signature'
     */
    @Test
    public void signatureTest() {
        // TODO: test signature
    }

    /**
     * Test the property 'mimeType'
     */
    @Test
    public void mimeTypeTest() {
        // TODO: test mimeType
    }

    /**
     * Test the property 'sizeOriginal'
     */
    @Test
    public void sizeOriginalTest() {
        // TODO: test sizeOriginal
    }

    /**
     * Test the property 'chunksTotal'
     */
    @Test
    public void chunksTotalTest() {
        // TODO: test chunksTotal
    }

    /**
     * Test the property 'chunksUploaded'
     */
    @Test
    public void chunksUploadedTest() {
        // TODO: test chunksUploaded
    }

}
