/*
 * Appwrite
 * Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: team@appwrite.io
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * File
 */
@ApiModel(description = "File")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class ModelFile {
  public static final String SERIALIZED_NAME_$_ID = "$id";
  @SerializedName(SERIALIZED_NAME_$_ID)
  private String $id;

  public static final String SERIALIZED_NAME_BUCKET_ID = "bucketId";
  @SerializedName(SERIALIZED_NAME_BUCKET_ID)
  private String bucketId;

  public static final String SERIALIZED_NAME_$_CREATED_AT = "$createdAt";
  @SerializedName(SERIALIZED_NAME_$_CREATED_AT)
  private String $createdAt;

  public static final String SERIALIZED_NAME_$_UPDATED_AT = "$updatedAt";
  @SerializedName(SERIALIZED_NAME_$_UPDATED_AT)
  private String $updatedAt;

  public static final String SERIALIZED_NAME_$_PERMISSIONS = "$permissions";
  @SerializedName(SERIALIZED_NAME_$_PERMISSIONS)
  private List<String> $permissions = new ArrayList<>();

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_SIGNATURE = "signature";
  @SerializedName(SERIALIZED_NAME_SIGNATURE)
  private String signature;

  public static final String SERIALIZED_NAME_MIME_TYPE = "mimeType";
  @SerializedName(SERIALIZED_NAME_MIME_TYPE)
  private String mimeType;

  public static final String SERIALIZED_NAME_SIZE_ORIGINAL = "sizeOriginal";
  @SerializedName(SERIALIZED_NAME_SIZE_ORIGINAL)
  private Integer sizeOriginal;

  public static final String SERIALIZED_NAME_CHUNKS_TOTAL = "chunksTotal";
  @SerializedName(SERIALIZED_NAME_CHUNKS_TOTAL)
  private Integer chunksTotal;

  public static final String SERIALIZED_NAME_CHUNKS_UPLOADED = "chunksUploaded";
  @SerializedName(SERIALIZED_NAME_CHUNKS_UPLOADED)
  private Integer chunksUploaded;

  public ModelFile() {
  }

  public ModelFile $id(String $id) {
    
    
    
    
    this.$id = $id;
    return this;
  }

   /**
   * File ID.
   * @return $id
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "File ID.")

  public String get$Id() {
    return $id;
  }


  public void set$Id(String $id) {
    
    
    
    this.$id = $id;
  }


  public ModelFile bucketId(String bucketId) {
    
    
    
    
    this.bucketId = bucketId;
    return this;
  }

   /**
   * Bucket ID.
   * @return bucketId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Bucket ID.")

  public String getBucketId() {
    return bucketId;
  }


  public void setBucketId(String bucketId) {
    
    
    
    this.bucketId = bucketId;
  }


  public ModelFile $createdAt(String $createdAt) {
    
    
    
    
    this.$createdAt = $createdAt;
    return this;
  }

   /**
   * File creation date in ISO 8601 format.
   * @return $createdAt
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "File creation date in ISO 8601 format.")

  public String get$CreatedAt() {
    return $createdAt;
  }


  public void set$CreatedAt(String $createdAt) {
    
    
    
    this.$createdAt = $createdAt;
  }


  public ModelFile $updatedAt(String $updatedAt) {
    
    
    
    
    this.$updatedAt = $updatedAt;
    return this;
  }

   /**
   * File update date in ISO 8601 format.
   * @return $updatedAt
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "File update date in ISO 8601 format.")

  public String get$UpdatedAt() {
    return $updatedAt;
  }


  public void set$UpdatedAt(String $updatedAt) {
    
    
    
    this.$updatedAt = $updatedAt;
  }


  public ModelFile $permissions(List<String> $permissions) {
    
    
    
    
    this.$permissions = $permissions;
    return this;
  }

  public ModelFile add$PermissionsItem(String $permissionsItem) {
    this.$permissions.add($permissionsItem);
    return this;
  }

   /**
   * File permissions. [Learn more about permissions](https://appwrite.io/docs/permissions).
   * @return $permissions
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "File permissions. [Learn more about permissions](https://appwrite.io/docs/permissions).")

  public List<String> get$Permissions() {
    return $permissions;
  }


  public void set$Permissions(List<String> $permissions) {
    
    
    
    this.$permissions = $permissions;
  }


  public ModelFile name(String name) {
    
    
    
    
    this.name = name;
    return this;
  }

   /**
   * File name.
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "File name.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    
    
    
    this.name = name;
  }


  public ModelFile signature(String signature) {
    
    
    
    
    this.signature = signature;
    return this;
  }

   /**
   * File MD5 signature.
   * @return signature
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "File MD5 signature.")

  public String getSignature() {
    return signature;
  }


  public void setSignature(String signature) {
    
    
    
    this.signature = signature;
  }


  public ModelFile mimeType(String mimeType) {
    
    
    
    
    this.mimeType = mimeType;
    return this;
  }

   /**
   * File mime type.
   * @return mimeType
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "File mime type.")

  public String getMimeType() {
    return mimeType;
  }


  public void setMimeType(String mimeType) {
    
    
    
    this.mimeType = mimeType;
  }


  public ModelFile sizeOriginal(Integer sizeOriginal) {
    
    
    
    
    this.sizeOriginal = sizeOriginal;
    return this;
  }

   /**
   * File original size in bytes.
   * @return sizeOriginal
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "File original size in bytes.")

  public Integer getSizeOriginal() {
    return sizeOriginal;
  }


  public void setSizeOriginal(Integer sizeOriginal) {
    
    
    
    this.sizeOriginal = sizeOriginal;
  }


  public ModelFile chunksTotal(Integer chunksTotal) {
    
    
    
    
    this.chunksTotal = chunksTotal;
    return this;
  }

   /**
   * Total number of chunks available
   * @return chunksTotal
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Total number of chunks available")

  public Integer getChunksTotal() {
    return chunksTotal;
  }


  public void setChunksTotal(Integer chunksTotal) {
    
    
    
    this.chunksTotal = chunksTotal;
  }


  public ModelFile chunksUploaded(Integer chunksUploaded) {
    
    
    
    
    this.chunksUploaded = chunksUploaded;
    return this;
  }

   /**
   * Total number of chunks uploaded
   * @return chunksUploaded
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Total number of chunks uploaded")

  public Integer getChunksUploaded() {
    return chunksUploaded;
  }


  public void setChunksUploaded(Integer chunksUploaded) {
    
    
    
    this.chunksUploaded = chunksUploaded;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ModelFile instance itself
   */
  public ModelFile putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelFile _file = (ModelFile) o;
    return Objects.equals(this.$id, _file.$id) &&
        Objects.equals(this.bucketId, _file.bucketId) &&
        Objects.equals(this.$createdAt, _file.$createdAt) &&
        Objects.equals(this.$updatedAt, _file.$updatedAt) &&
        Objects.equals(this.$permissions, _file.$permissions) &&
        Objects.equals(this.name, _file.name) &&
        Objects.equals(this.signature, _file.signature) &&
        Objects.equals(this.mimeType, _file.mimeType) &&
        Objects.equals(this.sizeOriginal, _file.sizeOriginal) &&
        Objects.equals(this.chunksTotal, _file.chunksTotal) &&
        Objects.equals(this.chunksUploaded, _file.chunksUploaded)&&
        Objects.equals(this.additionalProperties, _file.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash($id, bucketId, $createdAt, $updatedAt, $permissions, name, signature, mimeType, sizeOriginal, chunksTotal, chunksUploaded, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelFile {\n");
    sb.append("    $id: ").append(toIndentedString($id)).append("\n");
    sb.append("    bucketId: ").append(toIndentedString(bucketId)).append("\n");
    sb.append("    $createdAt: ").append(toIndentedString($createdAt)).append("\n");
    sb.append("    $updatedAt: ").append(toIndentedString($updatedAt)).append("\n");
    sb.append("    $permissions: ").append(toIndentedString($permissions)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    signature: ").append(toIndentedString(signature)).append("\n");
    sb.append("    mimeType: ").append(toIndentedString(mimeType)).append("\n");
    sb.append("    sizeOriginal: ").append(toIndentedString(sizeOriginal)).append("\n");
    sb.append("    chunksTotal: ").append(toIndentedString(chunksTotal)).append("\n");
    sb.append("    chunksUploaded: ").append(toIndentedString(chunksUploaded)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("$id");
    openapiFields.add("bucketId");
    openapiFields.add("$createdAt");
    openapiFields.add("$updatedAt");
    openapiFields.add("$permissions");
    openapiFields.add("name");
    openapiFields.add("signature");
    openapiFields.add("mimeType");
    openapiFields.add("sizeOriginal");
    openapiFields.add("chunksTotal");
    openapiFields.add("chunksUploaded");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("$id");
    openapiRequiredFields.add("bucketId");
    openapiRequiredFields.add("$createdAt");
    openapiRequiredFields.add("$updatedAt");
    openapiRequiredFields.add("$permissions");
    openapiRequiredFields.add("name");
    openapiRequiredFields.add("signature");
    openapiRequiredFields.add("mimeType");
    openapiRequiredFields.add("sizeOriginal");
    openapiRequiredFields.add("chunksTotal");
    openapiRequiredFields.add("chunksUploaded");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ModelFile
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ModelFile.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ModelFile is not found in the empty JSON string", ModelFile.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ModelFile.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("$id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `$id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("$id").toString()));
      }
      if (!jsonObj.get("bucketId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `bucketId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("bucketId").toString()));
      }
      if (!jsonObj.get("$createdAt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `$createdAt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("$createdAt").toString()));
      }
      if (!jsonObj.get("$updatedAt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `$updatedAt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("$updatedAt").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("$permissions") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("$permissions").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `$permissions` to be an array in the JSON string but got `%s`", jsonObj.get("$permissions").toString()));
      }
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (!jsonObj.get("signature").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `signature` to be a primitive type in the JSON string but got `%s`", jsonObj.get("signature").toString()));
      }
      if (!jsonObj.get("mimeType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `mimeType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("mimeType").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ModelFile.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ModelFile' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ModelFile> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ModelFile.class));

       return (TypeAdapter<T>) new TypeAdapter<ModelFile>() {
           @Override
           public void write(JsonWriter out, ModelFile value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ModelFile read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             ModelFile instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ModelFile given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ModelFile
  * @throws IOException if the JSON string is invalid with respect to ModelFile
  */
  public static ModelFile fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ModelFile.class);
  }

 /**
  * Convert an instance of ModelFile to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

