/*
 * Appwrite
 * Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: team@appwrite.io
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AvatarsApi
 */
@Disabled
public class AvatarsApiTest {

    private static AvatarsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new AvatarsApi(apiClient);
    }

    /**
     * Get QR code
     *
     * Converts a given plain text to a QR code image. You can use the query parameters to change the size and style of the resulting image. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void generateQrCodeImageTest() throws ApiException {
        String text = null;
        Integer size = null;
        Integer margin = null;
        Boolean download = null;
        api.generateQrCodeImage(text)
                .size(size)
                .margin(margin)
                .download(download)
                .execute();
        // TODO: test validations
    }

    /**
     * Get browser icon
     *
     * You can use this endpoint to show different browser icons to your users. The code argument receives the browser code as it appears in your user [GET /account/sessions](https://appwrite.io/docs/references/cloud/client-web/account#getSessions) endpoint. Use width, height and quality arguments to change the output settings.  When one dimension is specified and the other is 0, the image is scaled with preserved aspect ratio. If both dimensions are 0, the API provides an image at source quality. If dimensions are not specified, the default size of image returned is 100x100px.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getBrowserIconByCodeTest() throws ApiException {
        String code = null;
        Integer width = null;
        Integer height = null;
        Integer quality = null;
        api.getBrowserIconByCode(code)
                .width(width)
                .height(height)
                .quality(quality)
                .execute();
        // TODO: test validations
    }

    /**
     * Get country flag
     *
     * You can use this endpoint to show different country flags icons to your users. The code argument receives the 2 letter country code. Use width, height and quality arguments to change the output settings. Country codes follow the [ISO 3166-1](https://en.wikipedia.org/wiki/ISO_3166-1) standard.  When one dimension is specified and the other is 0, the image is scaled with preserved aspect ratio. If both dimensions are 0, the API provides an image at source quality. If dimensions are not specified, the default size of image returned is 100x100px. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCountryFlagByCodeTest() throws ApiException {
        String code = null;
        Integer width = null;
        Integer height = null;
        Integer quality = null;
        api.getCountryFlagByCode(code)
                .width(width)
                .height(height)
                .quality(quality)
                .execute();
        // TODO: test validations
    }

    /**
     * Get credit card icon
     *
     * The credit card endpoint will return you the icon of the credit card provider you need. Use width, height and quality arguments to change the output settings.  When one dimension is specified and the other is 0, the image is scaled with preserved aspect ratio. If both dimensions are 0, the API provides an image at source quality. If dimensions are not specified, the default size of image returned is 100x100px. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCreditCardIconTest() throws ApiException {
        String code = null;
        Integer width = null;
        Integer height = null;
        Integer quality = null;
        api.getCreditCardIcon(code)
                .width(width)
                .height(height)
                .quality(quality)
                .execute();
        // TODO: test validations
    }

    /**
     * Get favicon
     *
     * Use this endpoint to fetch the favorite icon (AKA favicon) of any remote website URL. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getFaviconTest() throws ApiException {
        String url = null;
        api.getFavicon(url)
                .execute();
        // TODO: test validations
    }

    /**
     * Get image from URL
     *
     * Use this endpoint to fetch a remote image URL and crop it to any image size you want. This endpoint is very useful if you need to crop and display remote images in your app or in case you want to make sure a 3rd party image is properly served using a TLS protocol.  When one dimension is specified and the other is 0, the image is scaled with preserved aspect ratio. If both dimensions are 0, the API provides an image at source quality. If dimensions are not specified, the default size of image returned is 400x400px. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getRemoteImageTest() throws ApiException {
        String url = null;
        Integer width = null;
        Integer height = null;
        api.getRemoteImage(url)
                .width(width)
                .height(height)
                .execute();
        // TODO: test validations
    }

    /**
     * Get user initials
     *
     * Use this endpoint to show your user initials avatar icon on your website or app. By default, this route will try to print your logged-in user name or email initials. You can also overwrite the user name if you pass the &#39;name&#39; parameter. If no name is given and no user is logged, an empty avatar will be returned.  You can use the color and background params to change the avatar colors. By default, a random theme will be selected. The random theme will persist for the user&#39;s initials when reloading the same theme will always return for the same initials.  When one dimension is specified and the other is 0, the image is scaled with preserved aspect ratio. If both dimensions are 0, the API provides an image at source quality. If dimensions are not specified, the default size of image returned is 100x100px. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getUserInitialsTest() throws ApiException {
        String name = null;
        Integer width = null;
        Integer height = null;
        String background = null;
        api.getUserInitials()
                .name(name)
                .width(width)
                .height(height)
                .background(background)
                .execute();
        // TODO: test validations
    }

}
